

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_app_production
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgres://postgres:your_password@db:5432/blog_app_production
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    stdin_open: true
    tty: true

volumes:
  pgdata:
